# Site settings
title: My Jekyll Site
description: A brief description of my Jekyll site

# URL settings
baseurl: "" # The subpath of your site, e.g., /blog
url: "http://example.com" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
